"""Reference VAM text assembler and interpreter."""
from .assembly import disassemble, parse_vmasm, read_vmasm
from .bytecode import decode_vmbc, encode_vmbc, read_vmbc, write_vmbc
from .compiler import CompileResult, VamCompileError, compile_expr, compile_source, compile_to_vmasm
from .diagnostics import (
    VamDiagnostic,
    VamDiagnosticResult,
    compile_source_diagnostic,
    compile_source_with_diagnostics,
)
from .dense import DENSE_MAGIC, DENSE_VERSION, DenseBytecodeError, decode_dense, dense_round_trip, encode_dense
from .errors import ERROR_PROFILE, TAXONOMY, boundary_error_row, classify_message, error_row, obstruction_error_row
from .equivalence import EquivalenceCheck, EquivalenceSummary, compare_optimizer_programs, summarize_equivalence
from .fixtures import (
    FixtureCase,
    fixture_program,
    fixture_report,
    fixture_report_program,
    iter_fixture_programs,
    iter_fixture_report_programs,
    iter_fixture_reports,
    iter_valid_vam0_fixture_report_programs,
)
from .highlevel import (
    HighLevelCompileResult,
    HighLevelDiagnostic,
    HighLevelLowering,
    compile_highlevel_source,
    lower_highlevel_source,
)
from .highlevel_v1 import HL1Diagnostic, HL1Lowering, lower_hl1_source
from .interpreter import execute, execute_with_definition_objects, run_vmasm
from .model import Instruction, TraceEvent, VamObject, VamState
from .obligation import (
    VamObligationRow,
    VamObligationStatus,
    obligation_batch_is_transport_only,
    obligation_instructions,
    obligation_json,
    obligation_rows_from_obligations,
    obligation_rows_from_theorem,
    obligation_status,
)
from .opcodes import (
    Arity,
    InstructionClassification,
    OpcodeSpec,
    OpcodeValidationError,
    classify_instruction,
    classify_program,
    get_opcode,
    opcode_rows,
    opcode_table,
    opcode_table_from_rows,
    validate_instruction,
)
from .optimizer import OptimizationReport, OptimizationRow, optimize
from .optimizer_completion import OptimizerTheoremSkeleton, VamdEmissionPolicy, VisibleUseGuardRow, optimizer_corpus_skeleton, optimizer_theorem_skeleton, vamd_optimized_emission_policy, visible_use_guard
from .optimizer_prepost import (
    OptimizerPrePostWitness,
    assert_no_optimizer_prepost_overclaim_terms,
    optimizer_prepost_witness_payload,
    optimizer_prepost_witness_rows,
    optimizer_prepost_witness_summary,
)
from .optimizer_obligations import (
    OptimizerObligation,
    OptimizerObligationCoverage,
    assert_no_overclaim_terms,
    optimizer_obligation_coverage,
    optimizer_obligation_coverage_payload,
    optimizer_obligation_payload,
    optimizer_obligation_rows,
    optimizer_obligation_summary,
)
from .optimizer_proofs import (
    OptimizerLeanCheckResult,
    OptimizerProofRow,
    OptimizerProofSummary,
    check_lean_optimizer_export,
    lean_optimizer_export_path,
    optimizer_proof_payload,
    optimizer_proof_rows,
    optimizer_proof_summary,
)
from .optimizer_witness import optimizer_witness_ledger, semantic_core_report, stable_digest
from .proof_objects import (
    NO_OVERCLAIM_BOUNDARY,
    ProofAtom,
    ProofBoundary,
    ProofConjunction,
    fold_status,
    normalize_status,
    proof_atom_from_case,
    proof_atom_from_shell_row,
    proof_conjunction_from_cases,
    proof_conjunction_from_shell_carrier,
    proof_object_json,
)
from .report import PROFILE, canonical_report, instruction_rows, register_rows, trace_rows
from .shell import NON_CERTIFICATE_BOUNDARY, ShellCarrier, ShellLoweringRow, decode_shell_carrier_label, lower_shell
from .theorem import (
    VamFiniteTheoremCase,
    VamTheoremEnvironment,
    VamTheoremObligation,
    VamTheoremRecord,
    lower_theorem_source,
    lower_theorem_statement,
)
from .quantified_theorem import NativeParityBoundary, QuantifiedBinder, QuantifiedTheoremInstruction, QuantifiedTheoremState, TheoremSpecialization, canonical_quantified_instruction, declare_quantified_theorem, native_quantified_parity_boundary, specialize_quantified_theorem

__all__ = [
    "Arity",
    "CompileResult",
    "DENSE_MAGIC",
    "DENSE_VERSION",
    "DenseBytecodeError",
    "ERROR_PROFILE",
    "EquivalenceCheck",
    "EquivalenceSummary",
    "FixtureCase",
    "HighLevelCompileResult",
    "HighLevelDiagnostic",
    "HighLevelLowering",
    "HL1Diagnostic",
    "HL1Lowering",
    "Instruction",
    "InstructionClassification",
    "NO_OVERCLAIM_BOUNDARY",
    "OptimizationReport",
    "NON_CERTIFICATE_BOUNDARY",
    "OptimizationRow",
    "OptimizerObligation",
    "OptimizerObligationCoverage",
    "OptimizerPrePostWitness",
    "OptimizerLeanCheckResult",
    "OptimizerProofRow",
    "OptimizerProofSummary",
    "OptimizerTheoremSkeleton",
    "OpcodeSpec",
    "OpcodeValidationError",
    "PROFILE",
    "ProofAtom",
    "ProofBoundary",
    "ProofConjunction",
    "QuantifiedBinder",
    "QuantifiedTheoremInstruction",
    "QuantifiedTheoremState",
    "ShellCarrier",
    "ShellLoweringRow",
    "TAXONOMY",
    "TraceEvent",
    "TheoremSpecialization",
    "NativeParityBoundary",
    "VamdEmissionPolicy",
    "VisibleUseGuardRow",
    "VamCompileError",
    "VamDiagnostic",
    "VamDiagnosticResult",
    "VamFiniteTheoremCase",
    "VamObject",
    "VamObligationRow",
    "VamObligationStatus",
    "VamState",
    "VamTheoremEnvironment",
    "VamTheoremObligation",
    "VamTheoremRecord",
    "boundary_error_row",
    "assert_no_overclaim_terms",
    "canonical_report",
    "canonical_quantified_instruction",
    "check_lean_optimizer_export",
    "classify_instruction",
    "classify_message",
    "classify_program",
    "compile_expr",
    "compile_highlevel_source",
    "compile_source",
    "compile_source_diagnostic",
    "compile_source_with_diagnostics",
    "compile_to_vmasm",
    "compare_optimizer_programs",
    "decode_shell_carrier_label",
    "decode_dense",
    "decode_vmbc",
    "declare_quantified_theorem",
    "dense_round_trip",
    "disassemble",
    "encode_dense",
    "encode_vmbc",
    "error_row",
    "execute",
    "execute_with_definition_objects",
    "fixture_program",
    "fixture_report",
    "fixture_report_program",
    "fold_status",
    "get_opcode",
    "instruction_rows",
    "iter_fixture_programs",
    "iter_fixture_report_programs",
    "iter_fixture_reports",
    "iter_valid_vam0_fixture_report_programs",
    "lean_optimizer_export_path",
    "lower_highlevel_source",
    "lower_hl1_source",
    "lower_shell",
    "lower_theorem_source",
    "lower_theorem_statement",
    "normalize_status",
    "native_quantified_parity_boundary",
    "obligation_batch_is_transport_only",
    "obligation_instructions",
    "obligation_json",
    "obligation_rows_from_obligations",
    "obligation_rows_from_theorem",
    "obligation_status",
    "obstruction_error_row",
    "opcode_rows",
    "opcode_table",
    "opcode_table_from_rows",
    "optimize",
    "optimizer_obligation_coverage",
    "optimizer_obligation_coverage_payload",
    "optimizer_obligation_payload",
    "optimizer_obligation_rows",
    "optimizer_obligation_summary",
    "assert_no_optimizer_prepost_overclaim_terms",
    "optimizer_prepost_witness_payload",
    "optimizer_prepost_witness_rows",
    "optimizer_prepost_witness_summary",
    "optimizer_proof_payload",
    "optimizer_proof_rows",
    "optimizer_proof_summary",
    "optimizer_witness_ledger",
    "optimizer_corpus_skeleton",
    "optimizer_theorem_skeleton",
    "parse_vmasm",
    "proof_atom_from_case",
    "proof_atom_from_shell_row",
    "proof_conjunction_from_cases",
    "proof_conjunction_from_shell_carrier",
    "proof_object_json",
    "register_rows",
    "read_vmasm",
    "read_vmbc",
    "run_vmasm",
    "semantic_core_report",
    "stable_digest",
    "summarize_equivalence",
    "specialize_quantified_theorem",
    "trace_rows",
    "validate_instruction",
    "vamd_optimized_emission_policy",
    "visible_use_guard",
    "write_vmbc",
]
