import VeyraPadicFamilyIntroduction

set_option autoImplicit false

/-- The compatible prime-power family generated by the natural power `p^k`. -/
def veyraPowerCarrier {p : Nat} (hp : VeyraPrimeWitness p) (k : Nat) :
    ZpVeyra hp :=
  veyraIntegerFamily hp (Int.ofNat (p ^ k))

/-- Raw literal equality on the candidate carrier; an exact `P_p` adapter is separate. -/
def veyraCarrierEq {p : Nat} (hp : VeyraPrimeWitness p)
    (x y : ZpVeyra hp) : Prop :=
  x = y

/-- The separator `p^(k+1)` is invisible through every coordinate `n <= k`. -/
theorem THM_P3N6_001_prefix_indistinguishable {p : Nat}
    (hp : VeyraPrimeWitness p) (k n : Nat) (h : n ≤ k) :
    veyraRho n (veyraIntegerFamily hp 0) =
      veyraRho n
        (veyraIntegerFamily hp (Int.ofNat (p ^ (k + 1)))) := by
  change veyraRho n (veyraIntegerFamily hp 0) =
    veyraRho n
      (veyraIntegerFamily hp (Int.ofNat (veyraModulus p k)))
  have hdvd : veyraModulus p n ∣ veyraModulus p k :=
    veyraModulusDvd hp n k h
  apply Fin.ext
  simp [veyraRho, veyraIntegerFamily, veyraIntegerResidue, Fin.intCast,
    hdvd, Nat.mod_eq_zero_of_dvd]

/-- The same separator becomes visible at the immediately following depth. -/
theorem THM_P3N6_002_next_depth_distinguishes {p : Nat}
    (hp : VeyraPrimeWitness p) (k : Nat) :
    veyraRho (k + 1) (veyraIntegerFamily hp 0) ≠
      veyraRho (k + 1)
        (veyraIntegerFamily hp (Int.ofNat (p ^ (k + 1)))) := by
  letI : NeZero (veyraModulus p (k + 1)) :=
    ⟨Nat.ne_of_gt (veyraModulusPos hp (k + 1))⟩
  change Fin.ofNat (veyraModulus p (k + 1)) 0 ≠
    Fin.ofNat (veyraModulus p (k + 1)) (veyraModulus p k)
  have hmod : veyraModulus p k < veyraModulus p (k + 1) := by
    have hpone : 1 < p := Nat.lt_of_lt_of_le Nat.one_lt_two hp.two_le
    exact Nat.pow_lt_pow_of_lt hpone
      (Nat.add_lt_add_right (Nat.lt_succ_self k) 1)
  intro equal
  have hval := congrArg Fin.val equal
  change 0 % veyraModulus p (k + 1) =
    veyraModulus p k % veyraModulus p (k + 1) at hval
  rw [Nat.zero_mod, Nat.mod_eq_of_lt hmod] at hval
  exact (Nat.ne_of_gt (veyraModulusPos hp k)) hval.symm

/-- Distinct natural powers determine distinct elements of this exact carrier. -/
theorem THM_P3N6_003_power_carrier_injective {p : Nat}
    (hp : VeyraPrimeWitness p) :
    Function.Injective (veyraPowerCarrier hp) := by
  intro k l equal
  have hpone : 1 < p := Nat.lt_of_lt_of_le Nat.one_lt_two hp.two_le
  have hk : p ^ k < veyraModulus p (k + l) := by
    simpa [veyraModulus] using
      Nat.pow_lt_pow_of_lt hpone
        (Nat.lt_succ_of_le (Nat.le_add_right k l))
  have hl : p ^ l < veyraModulus p (k + l) := by
    simpa [veyraModulus] using
      Nat.pow_lt_pow_of_lt hpone
        (Nat.lt_succ_of_le (Nat.le_add_left l k))
  letI : NeZero (veyraModulus p (k + l)) :=
    ⟨Nat.ne_of_gt (veyraModulusPos hp (k + l))⟩
  have hcoord := congrArg (veyraRho (k + l)) equal
  change Fin.ofNat (veyraModulus p (k + l)) (p ^ k) =
    Fin.ofNat (veyraModulus p (k + l)) (p ^ l) at hcoord
  have hval := congrArg Fin.val hcoord
  change p ^ k % veyraModulus p (k + l) =
    p ^ l % veyraModulus p (k + l) at hval
  rw [Nat.mod_eq_of_lt hk, Nat.mod_eq_of_lt hl] at hval
  rcases Nat.lt_trichotomy k l with hkl | hsame | hlk
  · exact False.elim ((Nat.ne_of_lt (Nat.pow_lt_pow_of_lt hpone hkl)) hval)
  · exact hsame
  · exact False.elim ((Nat.ne_of_gt (Nat.pow_lt_pow_of_lt hpone hlk)) hval)

/-- The same raw injection through literal carrier equality; this is not yet `PowerInjection`. -/
theorem THM_P3N6_004_power_carrier_eqc_injective {p : Nat}
    (hp : VeyraPrimeWitness p) (k l : Nat) :
    veyraCarrierEq hp (veyraPowerCarrier hp k)
      (veyraPowerCarrier hp l) -> k = l := by
  intro equal
  exact THM_P3N6_003_power_carrier_injective hp equal

/-- Exact adapter from the named raw carrier relation to Lean equality. -/
theorem THM_P3N6_005_carrier_equality_adapter {p : Nat}
    (hp : VeyraPrimeWitness p) (x y : ZpVeyra hp) :
    veyraCarrierEq hp x y ↔ x = y := by
  rfl

#print axioms THM_P3N6_001_prefix_indistinguishable
#print axioms THM_P3N6_002_next_depth_distinguishes
#print axioms THM_P3N6_003_power_carrier_injective
#print axioms THM_P3N6_004_power_carrier_eqc_injective
#print axioms THM_P3N6_005_carrier_equality_adapter
