"""Independent literal oracle data for the frozen P2-S registry."""

from __future__ import annotations

from .status_promotion_types import EvidenceStatus as S, JudgmentKind as K
from .status_promotion_types import PositiveProvenance as P

ORACLE_NONCLAIMS = (
    "ontology-completeness", "codebase-completeness", "retroactive-certification",
    "metaphysical-truth", "automatic-promotion",
)
ORACLE_FORBIDDEN_SOURCE_TYPES = (
    "bool", "digest-only", "old-certificate", "old-judgment", "finite-sample-table",
)
ORACLE_FORBIDDEN_CONCLUSION_FIELDS = (
    "exists", "global_exists", "metaphysically_exists", "proof_complete",
    "observer_independent", "physical_exists",
)
ORACLE_ASSUMPTION_POLICY_ID = "p2-s-acyclic-no-own-conclusion-v1"
ORACLE_STATEMENT_DIGESTS = (
    ("exact-snapshot-v1", "7193ddf2d2598a56b564c952bd80672daa46b01ddfdc023a9fc3dfadadce66a8"),
    ("doctrine-admission-v1", "29acbe874df8dff98f2449d87c15c2733e290029e4b40bb6bc08d09734087f72"),
    ("observer-execution-v1", "77f992c3889b415d3eef066b271f64d7a6f8e7b92c45ed5e3ecc7baa7dce96bc"),
    ("p1-b-finite-generation-v1", "9ec416f62b7fd2281f7c00c960714b89e01618999680fcca4373b07b0c8e45ec"),
    ("compatibility-replay-v1", "9239382e6465ae4cbb7492f9e7a645cf41f6a378dfb707527b05654ddf4f1fac"),
    ("continuation-replay-v1", "860055be19607289ba38e37fe654f8a0814496abe21952496a057bc5b767d2fc"),
    ("oep-observer-role-v1", "699348a474109f33edd49c14fd1d44db8895f204520682965dec71ed6a43b325"),
    ("hap-historical-actualization-v1", "f4204b625e0928e2a544c45fb7d146b740c639fb4bd89f1dd129ae02f33e7a54"),
    ("c2-c3-confluence-v1", "3f02f92e0f3db97a49d1f9969469dbcc88bce74196c672d5dc25ae33fa2e20ea"),
    ("a2-refinement-survival-v1", "250cda395a619a3b175c9163e7da0693f238ba283e778ee8c2e34d649f53d775"),
    ("sfp-scoped-formation-v1", "25da8e2a0ba45baf4cf1cef51e5ef77ba0f6633ad2b00ccbf84d41acf36a51c5"),
    ("afip-formally-derived-v1", "21a48d4860e79f97d5c7d1dd4c2af19ee2c492ad706e3b2247e1e828ddd0f0d3"),
    ("afip-supplied-hypothesis-v1", "aaedeed11fdd116b9ce16d687d570093a24dce0759726b3e94fa0df8900aa2a6"),
    ("afip-oracle-hypothesis-v1", "3db5e7193a0e4de30a07048d3205468c8f4442d5091c54cfc7c79601534218cf"),
    ("pomega-carrier-completion-v1", "821e8c8bac1552c9756c91a1eef564fc5e2b9ba1dbcea47ede5f080157b2d212"),
    ("network-invariance-v1", "f29a09e021441b88e09368ed0119dae9eadbc785d4632f41303b7af47514d3f2"),
    ("empirical-bridge-v1", "0698107b4e9439d9f7e78e760cdd5df65f5f93d69609a5973952221bc8745068"),
)

ORACLE_DOMAIN_ROWS = (
    (K.PRESENTED, (S.ESTABLISHED, S.OPEN), ((S.ESTABLISHED, P.SUPPLIED_PRESENTATION),)),
    (K.ADMISSIBLE, (S.ESTABLISHED_RELATIVE_TO_DOCTRINE, S.REFUTED, S.OPEN),
     ((S.ESTABLISHED_RELATIVE_TO_DOCTRINE, P.DOCTRINE_REPLAY),)),
    (K.OBSERVABLE, (S.ESTABLISHED_RELATIVE_TO_SCOPE, S.REFUTED, S.OPEN),
     ((S.ESTABLISHED_RELATIVE_TO_SCOPE, P.EXECUTABLE_REPLAY),
      (S.ESTABLISHED_RELATIVE_TO_SCOPE, P.FORMALLY_DERIVED))),
    (K.GENERABLE, (S.ESTABLISHED_RELATIVE_TO_SCOPE, S.REFUTED, S.OPEN),
     ((S.ESTABLISHED_RELATIVE_TO_SCOPE, P.EXECUTABLE_REPLAY),
      (S.ESTABLISHED_RELATIVE_TO_SCOPE, P.FORMALLY_DERIVED))),
    (K.COHERENT, (S.ESTABLISHED_RELATIVE_TO_SCOPE, S.REFUTED, S.OPEN),
     ((S.ESTABLISHED_RELATIVE_TO_SCOPE, P.EXECUTABLE_REPLAY),
      (S.ESTABLISHED_RELATIVE_TO_SCOPE, P.FORMALLY_DERIVED))),
    (K.PERSISTENT, (S.ESTABLISHED_RELATIVE_TO_SCOPE, S.REFUTED, S.OPEN),
     ((S.ESTABLISHED_RELATIVE_TO_SCOPE, P.EXECUTABLE_REPLAY),
      (S.ESTABLISHED_RELATIVE_TO_SCOPE, P.FORMALLY_DERIVED))),
    (K.CONFLUENT, (S.ESTABLISHED_RELATIVE_TO_SCOPE, S.REFUTED, S.OPEN),
     ((S.ESTABLISHED_RELATIVE_TO_SCOPE, P.EXECUTABLE_REPLAY),
      (S.ESTABLISHED_RELATIVE_TO_SCOPE, P.FORMALLY_DERIVED))),
    (K.REFINEMENT_ROBUST, (S.ESTABLISHED_RELATIVE_TO_SCOPE, S.REFUTED, S.OPEN),
     ((S.ESTABLISHED_RELATIVE_TO_SCOPE, P.EXECUTABLE_REPLAY),
      (S.ESTABLISHED_RELATIVE_TO_SCOPE, P.FORMALLY_DERIVED))),
    (K.OBSERVER_ROLE, (S.ESTABLISHED_RELATIVE_TO_SCOPE, S.OPEN),
     ((S.ESTABLISHED_RELATIVE_TO_SCOPE, P.DOCTRINE_REPLAY),)),
    (K.HISTORICALLY_ACTUALIZED, (S.ESTABLISHED_RELATIVE_TO_HISTORY, S.OPEN),
     ((S.ESTABLISHED_RELATIVE_TO_HISTORY, P.HISTORICAL_REPLAY),)),
    (K.SCOPED_OBJECT,
     (S.ESTABLISHED_RELATIVE_TO_FORMATION_SCOPE, S.REFUTED, S.OPEN),
     ((S.ESTABLISHED_RELATIVE_TO_FORMATION_SCOPE, P.DOCTRINE_REPLAY),)),
    (K.ALL_DEPTH_FAMILY, (S.ESTABLISHED_RELATIVE_TO_LEDGER, S.ASSUMED, S.OPEN),
     ((S.ESTABLISHED_RELATIVE_TO_LEDGER, P.FORMALLY_DERIVED),
      (S.ASSUMED, P.SUPPLIED_HYPOTHESIS), (S.ASSUMED, P.ORACLE_DEPENDENT))),
    (K.COMPLETED_CARRIER, (S.ESTABLISHED_RELATIVE_TO_LEDGER, S.REFUTED, S.OPEN),
     ((S.ESTABLISHED_RELATIVE_TO_LEDGER, P.FORMALLY_DERIVED),)),
    (K.OBJECTIVELY_STABLE,
     (S.ESTABLISHED_RELATIVE_TO_NETWORK, S.REFUTED, S.OPEN),
     ((S.ESTABLISHED_RELATIVE_TO_NETWORK, P.EXECUTABLE_REPLAY),
      (S.ESTABLISHED_RELATIVE_TO_NETWORK, P.FORMALLY_DERIVED))),
    (K.PHYSICALLY_INSTANTIATED,
     (S.ESTABLISHED_RELATIVE_TO_EMPIRICAL_BRIDGE, S.REFUTED, S.OPEN),
     ((S.ESTABLISHED_RELATIVE_TO_EMPIRICAL_BRIDGE, P.EMPIRICAL_BRIDGE),)),
)

ORACLE_RULE_ROWS = (
    ("exact-snapshot-v1", (("representation", "bounded-representation", ("canonical",),
      ("scope",)),), K.PRESENTED, S.ESTABLISHED, P.SUPPLIED_PRESENTATION,
     ("scope",), ORACLE_NONCLAIMS),
    ("doctrine-admission-v1", (("presentation", "presentation-artifact", ("canonical",),
      ("scope",)), ("doctrine", "doctrine-replay", ("admission",), ("doctrine",))),
     K.ADMISSIBLE, S.ESTABLISHED_RELATIVE_TO_DOCTRINE, P.DOCTRINE_REPLAY,
     ("doctrine", "scope"), ORACLE_NONCLAIMS),
    ("observer-execution-v1", (("coupling", "admitted-coupling", ("response",),
      ("doctrine", "observer")), ("input", "exact-input", ("input",), ("scope",))),
     K.OBSERVABLE, S.ESTABLISHED_RELATIVE_TO_SCOPE, P.EXECUTABLE_REPLAY,
     ("doctrine", "scope", "observer"), ORACLE_NONCLAIMS),
    ("p1-b-finite-generation-v1", (("seed", "seed-source", ("seed",), ("doctrine",)),
      ("program", "closed-program", ("replay",), ("scope", "stage"))), K.GENERABLE,
     S.ESTABLISHED_RELATIVE_TO_SCOPE, P.EXECUTABLE_REPLAY,
     ("doctrine", "scope", "stage"), ORACLE_NONCLAIMS),
    ("compatibility-replay-v1", (("relations", "exact-relations", ("relation-laws",),
      ("doctrine", "scope")), ("restrictions", "exact-restrictions",
      ("restriction-laws",), ("scope",))), K.COHERENT,
     S.ESTABLISHED_RELATIVE_TO_SCOPE, P.EXECUTABLE_REPLAY,
     ("doctrine", "scope"), ORACLE_NONCLAIMS),
    ("continuation-replay-v1", (("trace", "trace-artifact", ("trace",), ("history",)),
      ("continuation", "named-continuation", ("persistence",), ("scope",))),
     K.PERSISTENT, S.ESTABLISHED_RELATIVE_TO_SCOPE, P.EXECUTABLE_REPLAY,
     ("doctrine", "scope", "history"), ORACLE_NONCLAIMS),
    ("oep-observer-role-v1", (("genealogy", "oep-genealogy", ("genealogy",),
      ("scope", "observer")), ("recurrence", "oep-recurrence", ("recurrence",),
      ("scope", "observer")), ("discrimination", "oep-discrimination",
      ("discrimination",), ("scope", "observer")), ("persistence", "oep-persistence",
      ("persistence",), ("scope", "observer")), ("efficacy", "oep-efficacy",
      ("efficacy",), ("scope", "observer"))), K.OBSERVER_ROLE,
     S.ESTABLISHED_RELATIVE_TO_SCOPE, P.DOCTRINE_REPLAY,
     ("doctrine", "scope", "observer"), ORACLE_NONCLAIMS),
    ("hap-historical-actualization-v1", (("oep", "observer-role-artifact", ("role",),
      ("doctrine", "scope", "observer")), ("history", "birth-history",
      ("prior-history", "causal-pressure"), ("history",))), K.HISTORICALLY_ACTUALIZED,
     S.ESTABLISHED_RELATIVE_TO_HISTORY, P.HISTORICAL_REPLAY,
     ("doctrine", "scope", "history", "observer"), ORACLE_NONCLAIMS),
    ("c2-c3-confluence-v1", (("diagrams", "demanded-path-diagrams",
      ("coverage", "commutation"), ("doctrine", "scope", "history")),), K.CONFLUENT,
     S.ESTABLISHED_RELATIVE_TO_SCOPE, P.EXECUTABLE_REPLAY,
     ("doctrine", "scope", "history"), ORACLE_NONCLAIMS),
    ("a2-refinement-survival-v1", (("refinement", "genuine-refinement",
      ("strictness", "survival"), ("doctrine", "scope", "refinement")),),
     K.REFINEMENT_ROBUST, S.ESTABLISHED_RELATIVE_TO_SCOPE, P.EXECUTABLE_REPLAY,
     ("doctrine", "scope", "refinement"), ORACLE_NONCLAIMS),
    ("sfp-scoped-formation-v1", (("construction", "sfp-construction", ("construction",),
      ("doctrine", "scope")), ("support", "sfp-support", ("support",),
      ("doctrine", "scope")), ("g4", "sfp-g4", ("g4",), ("doctrine", "scope")),
      ("persistence", "sfp-persistence", ("persistence",), ("doctrine", "scope")),
      ("confluence", "sfp-confluence", ("confluence",), ("doctrine", "scope")),
      ("refinement", "sfp-refinement", ("refinement",), ("doctrine", "scope"))),
     K.SCOPED_OBJECT, S.ESTABLISHED_RELATIVE_TO_FORMATION_SCOPE, P.DOCTRINE_REPLAY,
     ("doctrine", "scope", "history"), ORACLE_NONCLAIMS),
    ("afip-formally-derived-v1", (("totality", "formal-totality-source",
      ("theorem", "formal-source"), ("ledger",)), ("restriction",
      "formal-restriction-laws", ("theorem",), ("family",)), ("ledger",
      "assumption-ledger", ("closure",), ("ledger",))), K.ALL_DEPTH_FAMILY,
     S.ESTABLISHED_RELATIVE_TO_LEDGER, P.FORMALLY_DERIVED,
     ("doctrine", "ledger", "family"), ORACLE_NONCLAIMS),
    ("afip-supplied-hypothesis-v1", (("hypothesis", "supplied-family-hypothesis",
      ("totality", "compatibility"), ("ledger", "family")),), K.ALL_DEPTH_FAMILY,
     S.ASSUMED, P.SUPPLIED_HYPOTHESIS, ("doctrine", "ledger", "family"),
     ORACLE_NONCLAIMS),
    ("afip-oracle-hypothesis-v1", (("oracle", "total-oracle-hypothesis",
      ("totality", "purity", "stability", "trust"), ("ledger", "family")),),
     K.ALL_DEPTH_FAMILY, S.ASSUMED, P.ORACLE_DEPENDENT,
     ("doctrine", "ledger", "family"), ORACLE_NONCLAIMS),
    ("pomega-carrier-completion-v1", (("carrier", "carrier-formation",
      ("constructor",), ("carrier",)), ("realization", "universal-realization",
      ("theorem",), ("ledger", "carrier")), ("separation", "joint-separation",
      ("theorem",), ("carrier",)), ("nonvacuity", "family-class-witness",
      ("witness",), ("ledger",))), K.COMPLETED_CARRIER,
     S.ESTABLISHED_RELATIVE_TO_LEDGER, P.FORMALLY_DERIVED,
     ("doctrine", "ledger", "carrier"), ORACLE_NONCLAIMS),
    ("network-invariance-v1", (("translations", "network-translations",
      ("preservation", "reflection", "domain"), ("network",)), ("confluence",
      "network-confluence", ("all-demanded",), ("history",)), ("refinements",
      "network-refinements", ("survival", "no-conflict"), ("scope",))),
     K.OBJECTIVELY_STABLE, S.ESTABLISHED_RELATIVE_TO_NETWORK, P.EXECUTABLE_REPLAY,
     ("doctrine", "scope", "network", "history"), ORACLE_NONCLAIMS),
    ("empirical-bridge-v1", (("measurement", "external-measurement",
      ("measurement", "provenance"), ("measurement",)), ("bridge",
      "empirical-doctrine", ("identification",), ("doctrine", "scope"))),
     K.PHYSICALLY_INSTANTIATED, S.ESTABLISHED_RELATIVE_TO_EMPIRICAL_BRIDGE,
     P.EMPIRICAL_BRIDGE, ("doctrine", "scope", "measurement"), ORACLE_NONCLAIMS),
)

ORACLE_PREMISE_PROJECTION_TRIPLES = (
    ("p2-project-exact-snapshot-v1-representation-v1", "exact-snapshot-v1", "representation"),
    ("p2-project-doctrine-admission-v1-presentation-v1", "doctrine-admission-v1", "presentation"),
    ("p2-project-doctrine-admission-v1-doctrine-v1", "doctrine-admission-v1", "doctrine"),
    ("p2-project-observer-execution-v1-coupling-v1", "observer-execution-v1", "coupling"),
    ("p2-project-observer-execution-v1-input-v1", "observer-execution-v1", "input"),
    ("p2-project-p1-b-finite-generation-v1-seed-v1", "p1-b-finite-generation-v1", "seed"),
    ("p2-project-p1-b-finite-generation-v1-program-v1", "p1-b-finite-generation-v1", "program"),
    ("p2-project-compatibility-replay-v1-relations-v1", "compatibility-replay-v1", "relations"),
    ("p2-project-compatibility-replay-v1-restrictions-v1", "compatibility-replay-v1", "restrictions"),
    ("p2-project-continuation-replay-v1-trace-v1", "continuation-replay-v1", "trace"),
    ("p2-project-continuation-replay-v1-continuation-v1", "continuation-replay-v1", "continuation"),
    ("p2-project-oep-observer-role-v1-genealogy-v1", "oep-observer-role-v1", "genealogy"),
    ("p2-project-oep-observer-role-v1-recurrence-v1", "oep-observer-role-v1", "recurrence"),
    ("p2-project-oep-observer-role-v1-discrimination-v1", "oep-observer-role-v1", "discrimination"),
    ("p2-project-oep-observer-role-v1-persistence-v1", "oep-observer-role-v1", "persistence"),
    ("p2-project-oep-observer-role-v1-efficacy-v1", "oep-observer-role-v1", "efficacy"),
    ("p2-project-hap-historical-actualization-v1-oep-v1", "hap-historical-actualization-v1", "oep"),
    ("p2-project-hap-historical-actualization-v1-history-v1", "hap-historical-actualization-v1", "history"),
    ("p2-project-c2-c3-confluence-v1-diagrams-v1", "c2-c3-confluence-v1", "diagrams"),
    ("p2-project-a2-refinement-survival-v1-refinement-v1", "a2-refinement-survival-v1", "refinement"),
    ("p2-project-sfp-scoped-formation-v1-construction-v1", "sfp-scoped-formation-v1", "construction"),
    ("p2-project-sfp-scoped-formation-v1-support-v1", "sfp-scoped-formation-v1", "support"),
    ("p2-project-sfp-scoped-formation-v1-g4-v1", "sfp-scoped-formation-v1", "g4"),
    ("p2-project-sfp-scoped-formation-v1-persistence-v1", "sfp-scoped-formation-v1", "persistence"),
    ("p2-project-sfp-scoped-formation-v1-confluence-v1", "sfp-scoped-formation-v1", "confluence"),
    ("p2-project-sfp-scoped-formation-v1-refinement-v1", "sfp-scoped-formation-v1", "refinement"),
    ("p2-project-afip-formally-derived-v1-totality-v1", "afip-formally-derived-v1", "totality"),
    ("p2-project-afip-formally-derived-v1-restriction-v1", "afip-formally-derived-v1", "restriction"),
    ("p2-project-afip-formally-derived-v1-ledger-v1", "afip-formally-derived-v1", "ledger"),
    ("p2-project-afip-supplied-hypothesis-v1-hypothesis-v1", "afip-supplied-hypothesis-v1", "hypothesis"),
    ("p2-project-afip-oracle-hypothesis-v1-oracle-v1", "afip-oracle-hypothesis-v1", "oracle"),
    ("p2-project-pomega-carrier-completion-v1-carrier-v1", "pomega-carrier-completion-v1", "carrier"),
    ("p2-project-pomega-carrier-completion-v1-realization-v1", "pomega-carrier-completion-v1", "realization"),
    ("p2-project-pomega-carrier-completion-v1-separation-v1", "pomega-carrier-completion-v1", "separation"),
    ("p2-project-pomega-carrier-completion-v1-nonvacuity-v1", "pomega-carrier-completion-v1", "nonvacuity"),
    ("p2-project-network-invariance-v1-translations-v1", "network-invariance-v1", "translations"),
    ("p2-project-network-invariance-v1-confluence-v1", "network-invariance-v1", "confluence"),
    ("p2-project-network-invariance-v1-refinements-v1", "network-invariance-v1", "refinements"),
    ("p2-project-empirical-bridge-v1-measurement-v1", "empirical-bridge-v1", "measurement"),
    ("p2-project-empirical-bridge-v1-bridge-v1", "empirical-bridge-v1", "bridge"),
)

ORACLE_INDEX_PROJECTION = (
    "p2-exists-generable-stage-v1", K.GENERABLE,
    ("doctrine", "scope", "stage"), "stage", ("doctrine", "scope"),
)
